#!/Library/Frameworks/Python.framework/Versions/3.9/bin/python3
"""
filtro para leitura de varios ficheiro passados em linha de comando

...
"""
import sys
from getopt import getopt
from re import *
from pickle import *
import spacy 




# vai chamar-se interact e sera a função que usa o spacy para encontrar ralaçoes entre as personagens.
def procFam(f, i):
    pass

# vai divir livro por capitulos e usar a funçao interact em cada um.
def procTexto(t):
    text2 = sub(r'\f', '', txt)
    text3 = sub(r'\n\n+', '\n', text2)
    text4 = sub(r'(\n[A-z])\n', r'\n\1', text3)
    # apartir daqui o texto parece estar mais ou menos organizado para fazer o resto.
    print(text4)
    #items = split(r'\n0', t)

ops,args = getopt(sys.argv[1:],"a:o:")
ops = dict(ops)
for ficheiro in args:
    with open(ficheiro) as f :
        txt = f.read()
    #processar o texto
    procTexto(txt)


#  rever isto do pickle ---- Pickler.dump()

#diferentes opçoes
if '-a' in ops:
    pass
    #gTree(ops["-a"])


